### ISSUE TITLE
test #3 failed

### ISSUE THREAD

**Issue by Do4Net** [Do4Net/pack4gulp-es6-webpack#1]
Build 'test' is failing!

Last 50 lines of build output:

```
Started by user jianfa
Building in workspace C:\Program Files (x86)\Jenkins\workspace\test
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe init C:\Program Files (x86)\Jenkins\workspace\test # timeout=10
Fetching upstream changes from https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe --version # timeout=10
using GIT_ASKPASS to set credentials githubusername
 > C:/Program Files/Git/git-cmd.exe fetch --tags https://github.com/Do4Net/pack4gulp-es6-webpack.git +refs/heads/*:refs/remotes/origin/*
 > C:/Program Files/Git/git-cmd.exe config remote.origin.url https://github.com/Do4Net/pack4gulp-es6-webpack.git # timeout=10
 > C:/Program Files/Git/git-cmd.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > C:/Program Files/Git/git-cmd.exe config remote.origin.url https://github.com/Do4Net/pack4gulp-es6-webpack.git # timeout=10
Fetching upstream changes from https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe --version # timeout=10
using GIT_ASKPASS to set credentials githubusername
 > C:/Program Files/Git/git-cmd.exe fetch --tags https://github.com/Do4Net/pack4gulp-es6-webpack.git +refs/heads/*:refs/remotes/origin/*
 > C:/Program Files/Git/git-cmd.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
FATAL: Invalid id: C:\Program Files (x86)\Jenkins\workspace\test>
org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: C:\Program Files (x86)\Jenkins\workspace\test>
	at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:232)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:689)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.util.DefaultBuildChooser.getHeadRevision(DefaultBuildChooser.java:130)
	at hudson.plugins.git.util.DefaultBuildChooser.getCandidateRevisions(DefaultBuildChooser.java:112)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:992)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1095)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

```

Changes since last successful build:

[View full output](http://112.74.90.24:8080/job/test/3/)

**Comment by Do4Net** [comment]
Build 'test' is failing!

Last 50 lines of build output:

```
Started by user jianfa
Building in workspace C:\Program Files (x86)\Jenkins\workspace\test
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe init C:\Program Files (x86)\Jenkins\workspace\test # timeout=10
Fetching upstream changes from https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe --version # timeout=10
using GIT_ASKPASS to set credentials githubusername
 > C:/Program Files/Git/git-cmd.exe fetch --tags https://github.com/Do4Net/pack4gulp-es6-webpack.git +refs/heads/*:refs/remotes/origin/*
 > C:/Program Files/Git/git-cmd.exe config remote.origin.url https://github.com/Do4Net/pack4gulp-es6-webpack.git # timeout=10
 > C:/Program Files/Git/git-cmd.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > C:/Program Files/Git/git-cmd.exe config remote.origin.url https://github.com/Do4Net/pack4gulp-es6-webpack.git # timeout=10
Fetching upstream changes from https://github.com/Do4Net/pack4gulp-es6-webpack.git
 > C:/Program Files/Git/git-cmd.exe --version # timeout=10
using GIT_ASKPASS to set credentials githubusername
 > C:/Program Files/Git/git-cmd.exe fetch --tags https://github.com/Do4Net/pack4gulp-es6-webpack.git +refs/heads/*:refs/remotes/origin/*
 > C:/Program Files/Git/git-cmd.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
FATAL: Invalid id: C:\Program Files (x86)\Jenkins\workspace\test>
org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: C:\Program Files (x86)\Jenkins\workspace\test>
	at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:232)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:689)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.util.DefaultBuildChooser.getHeadRevision(DefaultBuildChooser.java:130)
	at hudson.plugins.git.util.DefaultBuildChooser.getCandidateRevisions(DefaultBuildChooser.java:112)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:992)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1095)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

```

Changes since last successful build:


[View full output](http://112.74.90.24:8080/job/test/4/)

**Comment by Do4Net** [comment]
Build was fixed!
